server:
  port: 8080
  origin: ${ORIGIN:*}
  servlet:
    context-path: /commands
spring:
  application:
    name: gamecommands
  main:
    lazy-initialization: true
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  rabbitmq:
    addresses: ${RABBITMQ_URI:amqp://guest:guest@localhost:5672}

microservice:
  exchange: ${EXCHANGE:core-game}
  queue: ${QUEUE:game.commandhandles}
  storeName: ${STORE_NAME:game}
  routingKey: ${ROUTING_KEY:cardgame.#}

amazon:
  dynamodb:
    endpoint: http://localhost:4566/
  aws:
    accesskey: key
    secretkey: key2


