server:
  port: 8081
  origin: ${ORIGIN:*}
  servlet:
    context-path: /queries
spring:
  main:
    lazy-initialization: true
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: game-queries
  rabbitmq:
    addresses: ${RABBITMQ_URI:amqp://guest:guest@localhost:5672}  
  data:
    mongodb:
        uri: ${MONGO_URI:mongodb://localhost:27017/test}
microservice:
  exchange: ${EXCHANGE:core-game}
  queue: ${QUEUE:game.queryhandles}
  routingKey: ${ROUTING_KEY:cardgame.#}