server:
  port: 8082
  origin: ${ORIGIN:*}
  servlet:
    context-path: /proxy
spring:
  main:
    lazy-initialization: true
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: game-proxy
  rabbitmq:
    addresses: ${RABBITMQ_URI:amqp://guest:guest@localhost:5672}
microservice:
  exchange: ${EXCHANGE:core-game}
  queue: ${QUEUE:game.proxyhandles}
  routingKey: ${ROUTING_KEY:cardgame.#}